import { navigate } from "../lib/navigation";
import { nextAction, parseRunConfiguration, workflowStages } from "../lib/workflow";
import type { StatusSummary } from "../lib/types";
import { Button, Metric, PageHeader, Panel, ProgressBar, StatusBadge, formatDate, formatNumber, titleCase } from "../components/ui";

export default function Overview({ status, refresh }: { status: StatusSummary; refresh: () => Promise<void> }) {
  const stages = workflowStages(status);
  const complete = stages.filter((stage) => stage.state === "complete").length;
  const action = nextAction(status);
  const cues = Object.entries(status.exceptions ?? {});
  const openReviews = Object.values(status.review_status ?? {}).reduce((sum, value) => sum + value, 0);
  const runConfig = parseRunConfiguration(status.latest_run);
  const glImports = status.imports.filter((item) => item.kind === "gl");

  return <div className="overview-page"><PageHeader eyebrow="ENGAGEMENT COMMAND CENTRE" title="Good work starts with the next action." description="A clear view of what is complete, what needs attention, and which evidence supports the next decision." action={<Button variant="secondary" onClick={() => void refresh()}>Refresh status</Button>} />
    <div className="overview-status-row"><Panel className="overview-status-panel"><div className="panel-topline"><div><div className="eyebrow">ENGAGEMENT STATUS</div><h2>{status.engagement?.client ?? "Unnamed engagement"}</h2><p>{status.engagement ? `${formatDate(status.engagement.period_start)} — ${formatDate(status.engagement.period_end)}` : "Create an engagement to begin"}</p></div><StatusBadge tone={status.review_set.locked ? "success" : "indigo"} dot>{status.review_set.locked ? "Review set locked" : "Review in progress"}</StatusBadge></div><ProgressBar value={(complete / stages.length) * 100} label={`${complete} of ${stages.length} stages complete`} /><div className="status-footer"><span><strong>{status.entries.toLocaleString("en-IN")}</strong> ledger entries</span><span><strong>{status.latest_run.id ? `Run ${status.latest_run.id}` : "No analysis run"}</strong> current analysis</span><span><strong>{status.review_set.locked ? "Locked" : "Open"}</strong> review set</span></div></Panel><Panel className={`next-action-panel next-action-${action.tone}`}><div className="next-action-icon" aria-hidden="true">{action.tone === "green" ? "✓" : action.tone === "amber" ? "!" : "→"}</div><div className="eyebrow">{action.eyebrow}</div><h2>{action.title}</h2><p>{action.description}</p><Button variant="primary" onClick={() => navigate(action.screen)}>{action.cta}<span aria-hidden="true">→</span></Button></Panel></div>
    <div className="metric-strip"><Metric label="Ledger entries" value={formatNumber(status.entries)} detail={glImports.length ? `${glImports.length} GL version${glImports.length === 1 ? "" : "s"}` : "No ledger yet"} /><Metric label="Rejected rows" value={formatNumber(status.rejected_rows)} detail={status.rejected_rows ? "Review population quality" : "No rejected rows"} tone={status.rejected_rows ? "amber" : "neutral"} /><Metric label="Risk cues" value={formatNumber(cues.reduce((sum, [, count]) => sum + count, 0))} detail={status.latest_run.id ? `Run ${status.latest_run.id}` : "Awaiting analysis"} tone="indigo" /><Metric label="Open reviews" value={formatNumber(status.review_status.open ?? 0)} detail={openReviews ? `${openReviews} recorded state${openReviews === 1 ? "" : "s"}` : "No reviews recorded"} /><Metric label="Testing sample" value={status.sample_sets?.length ? formatNumber(status.sample_sets[0].id) : "—"} detail={status.sample_sets?.length ? "Latest proposed sample" : "Not created"} tone={status.sample_sets?.length ? "green" : "neutral"} /></div>
    <div className="overview-lower"><Panel className="workflow-panel"><div className="section-heading"><div><div className="eyebrow">WORKFLOW</div><h2>Engagement stages</h2></div><span className="muted-label">Select a stage to continue</span></div><div className="stage-list">{stages.map((stage, index) => <button className={`stage-row stage-${stage.state}`} key={stage.key} onClick={() => navigate(stage.screen)}><span className="stage-index">{String(index + 1).padStart(2, "0")}</span><span className={`stage-marker stage-marker-${stage.state}`}>{stage.state === "complete" ? "✓" : stage.state === "blocked" ? "!" : stage.state === "current" ? "●" : "○"}</span><span className="stage-copy"><strong>{stage.label}</strong><small>{stage.detail}</small></span><span className="stage-state-label">{stage.state === "complete" ? "Complete" : stage.state === "current" ? "Current" : stage.state === "blocked" ? "Attention" : "Not started"}</span><span className="stage-arrow">→</span></button>)}</div></Panel><div className="overview-side"><Panel className="activity-preview"><div className="section-heading"><div><div className="eyebrow">LATEST ANALYSIS</div><h2>Run context</h2></div><Button variant="quiet" size="sm" onClick={() => navigate("analysis")}>Open analysis</Button></div>{status.latest_run.id ? <><div className="run-summary"><div><span>Run</span><strong>#{status.latest_run.id}</strong></div><div><span>Status</span><StatusBadge tone="success" dot>{titleCase(status.latest_run.status ?? "unknown")}</StatusBadge></div><div><span>Population</span><strong>{formatNumber(status.latest_run.population_count ?? 0)}</strong></div></div><p className="muted-copy">{(runConfig.tests as string[] | undefined)?.length ? `${(runConfig.tests as string[]).length} governed checks recorded.` : "Versioned analysis context is preserved with this run."}</p><div className="cue-breakdown">{cues.length ? cues.map(([severity, count]) => <div key={severity}><span>{titleCase(severity)}</span><strong>{formatNumber(count)}</strong></div>) : <p className="muted-copy">No risk cues have been generated yet.</p>}</div></> : <div className="side-empty"><span>◌</span><p>Run analysis after population acknowledgement to see ranked cues here.</p><Button size="sm" onClick={() => navigate("analysis")}>Open analysis</Button></div>}</Panel><Panel className="trace-preview"><div className="eyebrow">TRACEABILITY</div><h2>Evidence stays attached.</h2><p>Source lineage, acknowledgements, assignments, reviews, lock events, and exports remain available in the audit trail.</p><Button variant="secondary" size="sm" onClick={() => navigate("activity")}>Open audit trail <span>→</span></Button></Panel></div></div>
    <div className="overview-disclaimer"><span className="status-dot" />Risk scores prioritize human review. This workbench does not make audit conclusions or determinations.</div>
  </div>;
}
